### PR TITLE
[build] Add pr-jobs-linux check

### LINKED ISSUE #6: [Task] Migrate CI to Github actions
**What is this for**
Currently the CI is hosted on CircleCI which involves outside support. A considerable way is to migrate it to Github Actions using github runners.

**Describe the solution you'd like**
Write a ci script under .github

### PR DESCRIPTION
**Pull request by fredia**
## What is the purpose of the change

Add pr-jobscheck, pr-jobs.yml is a simplified version of https://github.com/facebook/rocksdb/blob/main/.github/workflows/pr-jobs.yml, which only contains some checks on basic linux and macOS. 
Since we are using the shared github machine as the runner, there are some minor differences:
1. `build-linux` and `build-linux-release` require gflags to be installed first.
2. The threads of `build-linux` are decreased from 32 to 8, to prevent accidental cancellation.
3. The timeout of each job is increased to 120 min.

## Brief change log

  - Add pr-jobs.yml

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

### CODE REVIEW

**Comment by Zakelly** [comment]
@fredia Would you please share the diff of this scripts with those in rocksdb repo?

**Comment by fredia** [comment]
> @fredia Would you please share the diff of this scripts with those in rocksdb repo?

Sure, I updated the diff in the description, PTAL.

**Comment by Zakelly** [comment]
@fredia Great job!  Is it possible to add CI for macosx?

**Comment by fredia** [comment]
> @fredia Great job! Is it possible to add CI for macosx?

Added `build-macOS`, `build-macOS-java` and `build-macOS-java-static`, PTAL.

**Review by Zakelly — APPROVED** [review]
@fredia Good job! LGTM +1

**Comment by Zakelly** [comment]
This closes #6

**Pull request merged**
